name: Deploy OrderItemsReserver Azure Function

on:
  push:
    branches:
      - main
#    paths:
#      - 'src/OrderItemsReserver/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/OrderItemsReserver/OrderItemsReserver.csproj

      - name: Build
        run: dotnet build src/OrderItemsReserver/OrderItemsReserver.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/OrderItemsReserver/OrderItemsReserver.csproj --configuration Release --no-build --output ./publish

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v2
        with:
          app-name: OrderItemsReserver-eshopuksouth
          package: ./publish
          publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE_API_SOUTH }}
          scm-do-build-during-deployment: false
          enable-oryx-build: false
